name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend deps
        run: |
          cd frontend || exit 0
          if [ -f package.json ]; then npm ci; fi
      - name: Install backend deps
        run: |
          cd backend || exit 0
          if [ -f package.json ]; then npm ci; fi
      - name: Run linters (placeholder)
        run: |
          echo "Add lint/test steps"
